---
# SPDX-FileCopyrightText: 2023 The Linux Foundation
# SPDX-License-Identifier: Apache-2.0
ci:
  autofix_commit_msg: "Chore: pre-commit autoupdate"

exclude: "^docs/conf.py"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b # frozen: 5.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: no-commit-to-branch
        args:
          - --branch=dev
          - --branch=master
          - --branch=main
          - --branch=rc
          - --branch=production

  - repo: https://github.com/jorisroovers/gitlint
    rev: acc9d9de6369b76d22cb4167029d2035e8730b98 # frozen: v0.19.1
    hooks:
      - id: gitlint

  - repo: https://github.com/adrienverge/yamllint.git
    rev: 81e9f98ffd059efe8aa9c1b1a42e5cce61b640c6 # frozen: v1.35.1
    hooks:
      - id: yamllint
        types: [yaml]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 75b98813cfb7e663870a28c74366a1e99d7bfe79 # frozen: v0.6.9
    hooks:
      - id: ruff
        files: ^(scripts|tests|custom_components)/.+\.py$
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
        files: ^(scripts|tests|custom_components)/.+\.py$

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: f12edd9c7be1c20cfa42420fd0e6df71e42b51ea # frozen: v4.0.0-alpha.8
    hooks:
      - id: prettier
        stages: [commit]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 8cd2d4056637e242709fe09f15a36f0b4b682bda # frozen: v1.8.0
    hooks:
      - id: mypy

  - repo: https://github.com/btford/write-good
    rev: ab66ce10136dfad5146e69e70f82a3efac8842c1 # frozen: v1.0.8
    hooks:
      - id: write-good
        files: "\\.(rst|md|markdown|mdown|mkdn)$"

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: a23f6b85d0fdd5bb9d564e2579e678033debbdff # frozen: v0.10.0.1
    hooks:
      - id: shellcheck

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: aa975a18c9a869648007d33864034dbc7481fe5e # frozen: v0.42.0
    hooks:
      - id: markdownlint
        args: ["--fix"]

  - repo: https://github.com/fsfe/reuse-tool
    rev: 97607144d9c340262236b6eb1cf7b605e9a5880a # frozen: v4.0.3
    hooks:
      - id: reuse

  # Replaces: https://github.com/rhysd/actionlint
  # Permits actionlint to run both locally and with precommit.ci/GitHub
  - repo: https://github.com/Mateusz-Grzelinski/actionlint-py
    rev: e676b4576ddcc3018077da2c172f30a3a83974eb # frozen: v1.7.3.17
    hooks:
      - id: actionlint
