---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2023 The Linux Foundation

name: "gradle-build"
description: "Setup a specific JDK version and run gradle build"

inputs:
  jdk-version:
    description: "OpenJDK version"
    required: false

runs:
  using: "composite"
  steps:
    - name: Setup JDK
      id: setup-jdk
      # yamllint disable-line rule:line-length
      uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b # v4.6.0
      with:
        java-version: ${{ inputs.jdk-version }}
        distribution: "temurin"
    - name: Setup Gradle
      id: setup-gradle
      # yamllint disable-line rule:line-length
      uses: gradle/gradle-build-action@ac2d340dc04d9e1113182899e983b5400c17cda1 # v3.5.0
    - name: Run build with Gradle Wrapper
      id: run-gradle-build
      shell: bash
      run: ./gradlew build
