---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2023 The Linux Foundation

name: Composed Generic Sonar Cloud

# yamllint disable-line rule:truthy
on:
  workflow_call:
    inputs:
      GERRIT_BRANCH:
        description: "Branch that change is against"
        required: true
        type: string
      GERRIT_CHANGE_ID:
        description: "The ID for the change"
        required: true
        type: string
      GERRIT_CHANGE_NUMBER:
        description: "The Gerrit number"
        required: true
        type: string
      GERRIT_CHANGE_URL:
        description: "URL to the change"
        required: true
        type: string
      GERRIT_EVENT_TYPE:
        description: "Type of Gerrit event"
        required: true
        type: string
      GERRIT_PATCHSET_NUMBER:
        description: "The patch number for the change"
        required: true
        type: string
      GERRIT_PATCHSET_REVISION:
        description: "The revision sha"
        required: true
        type: string
      GERRIT_PROJECT:
        description: "Project in Gerrit"
        required: true
        type: string
      GERRIT_REFSPEC:
        description: "Gerrit refspec of change"
        required: true
        type: string
      JDK_VERSION:
        description: "OpenJDK version"
        required: false
        type: string
      ENV_VARS:
        # yamllint disable-line rule:line-length
        description: "Pass GitHub variables to be exported as environment variables via `toJSON(vars)` or specific variables encoded in JSON format"
        required: false
        type: string
      ENV_SECRETS:
        # yamllint disable-line rule:line-length
        description: "Pass GitHub secrets to be exported as environment variables via `toJSON(secrets)` or specific secrets encoded in JSON format"
        required: false
        type: string
      PRE_BUILD_SCRIPT:
        description: "Optional pre-build script to trigger before verify run"
        required: false
        default: ""
        type: string
      SONAR_ARGS:
        description: "Additional arguments to the SonarCloud scanner"
        required: false
        type: string
        default: ""
      SONAR_PROJECTBASEDIR:
        description: "Set the sonar.projectBaseDir analysis property"
        required: false
        type: string
        default: .
    secrets:
      SONAR_TOKEN:
        description: "Sonar Cloud access token"
        required: true

concurrency:
  # yamllint disable-line rule:line-length
  group: composed-generic-sonar-cloud-${{ github.workflow }}-${{ github.event.inputs.GERRIT_BRANCH}}-${{ github.event.inputs.GERRIT_CHANGE_ID || github.run_id }}
  cancel-in-progress: true

jobs:
  run-generic-sonar-scan:
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{ inputs.GERRIT_BRANCH }}
          submodules: "true"
      # yamllint disable-line rule:line-length
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        id: setup-python
        with:
          python-version: "3.8"
      - name: Setup JDK
        id: setup-jdk
        # yamllint disable-line rule:line-length
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          java-version: ${{ inputs.JDK_VERSION }}
          distribution: "temurin"
      - name: Export env variables
        id: export-env-variables
        # yamllint disable-line rule:line-length
        uses: infovista-opensource/vars-to-env-action@3d3e7c8ae1e9e5fcd9ce83e56ab85a6a135d2ffa # v2.0.0
        with:
          secrets: ${{ inputs.ENV_VARS }}
      - name: Export env secrets
        id: export-env-secrets
        # yamllint disable-line rule:line-length
        uses: infovista-opensource/vars-to-env-action@3d3e7c8ae1e9e5fcd9ce83e56ab85a6a135d2ffa # v2.0.0
        with:
          secrets: ${{ inputs.ENV_SECRETS }}
      - name: Run pre-build-script
        id: pre-build
        if: ${{ hashFiles(inputs.PRE_BUILD_SCRIPT) }}
        shell: bash
        run: ${{ inputs.PRE_BUILD_SCRIPT }}
      - name: Run Sonar Cloud scan
        # yamllint disable-line rule:line-length
        uses: lfreleng-actions/sonarqube-cloud-scan-action@bad9028f5252eb1432340d891f9b3a589f0280c1 # v0.1.2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
