---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation

# Runs a Sonatype Lifecycle (Nexus IQ) scan
name: "[R] sonatype-lifecycle"

# yamllint disable-line rule:truthy
on:
  workflow_call:
    inputs:
      JAVA_DISTRIBUTION:
        description: "JAVA SE distribution to setup/run for Nexus CLI tool"
        required: false
        type: string
        default: "temurin"
      JAVA_VERSION:
        description: "Java runtime to setup/run for Nexus CLI tool"
        required: false
        type: number
        default: 17
      IQ_CLI_VERSION:
        description: "Specific version of Nexus CLI to setup/run"
        required: false
        type: string
        default: "1.179.0-01"
      APPLICATION_ID:
        description: "Organisation and project name in Nexus IQ"
        required: false
        type: string
        # yamllint disable-line rule:line-length
        default: ${{ github.repository_owner }}-${{ github.event.repository.name }}
      SCAN_TARGETS:
        description: "Location of file(s) or folder(s) to scan"
        required: false
        type: string
        default: "."
    # Re-usable workflow requires secrets be explicitly passed
    secrets:
      NEXUS_IQ_PASSWORD:
        description: "Nexus IQ Password"
        required: true

jobs:
  sonatype-cli:
    name: "Scan"
    runs-on: ubuntu-latest
    steps:
      - name: Setup Sonatype CLI
        # yamllint disable-line rule:line-length
        uses: sonatype/actions/setup-iq-cli@5cda9c26ba3a6fab47a8870695d634cee81da062 # v.1.1.2
        with:
          iq-cli-version: ${{ inputs.IQ_CLI_VERSION }}

      # Sonatype CLI requires Java to run
      - name: Setup Java runtime
        # yamllint disable-line rule:line-length
        uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b # v4.6.0
        with:
          distribution: ${{ inputs.JAVA_DISTRIBUTION }}
          java-version: ${{ inputs.JAVA_VERSION }}

      - name: Run Sonatype CLI
        # yamllint disable-line rule:line-length
        uses: sonatype/actions/run-iq-cli@5cda9c26ba3a6fab47a8870695d634cee81da062 # v1.1.2
        with:
          iq-server-url: ${{ vars.NEXUS_IQ_SERVER }}
          username: ${{ vars.NEXUS_IQ_USERNAME }}
          password: ${{ secrets.NEXUS_IQ_PASSWORD }}
          application-id: ${{ inputs.APPLICATION_ID }}
          scan-targets: ${{ inputs.SCAN_TARGETS }}
