---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# Verifies action/workflow calls are pinned to SHA commit values
name: '📌 [R] Audit GitHub Actions'

# yamllint disable-line rule:truthy
on:
  workflow_call:

permissions: {}

jobs:
  check-actions:
    name: 'Pinned Versions'
    runs-on: 'ubuntu-24.04'
    permissions:
      contents: read
    steps:
      - name: 'Check Pinned Versions'
        # yamllint disable-line rule:line-length
        uses: lfreleng-actions/pinned-versions-action@1deefbe98d5f8e463ffd3943d5019fdfb7931ab0 # v0.1.1
