---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation

# Runs a SonarQube Cloud scan
name: "[R] SonarQube Cloud"

# yamllint disable-line rule:truthy
on:
  workflow_call:
    inputs:
      # Optional
      sonar_root_cert:
        description: "Server root certificate PEM encoded"
        type: string
        required: false
      build_wrapper_url:
        # yamllint disable-line rule:line-length
        # e.g. https://raw.githubusercontent.com/o-ran-sc/ci-management/refs/heads/master/jjb/com-golog/prescan-golog-go-ubuntu.sh
        description: "Download location of build wrapper/script"
        type: string
        required: false
      build_wrapper_out_dir:
        description: "Filesystem location of build outputs"
        type: string
        required: false
      sonar_host_url:
        description: "Uploads scans to the given host URL"
        type: string
        required: false
        default: "https://sonarcloud.io"
      lc_all:
        # yamllint disable-line rule:line-length
        description: "Change when code character set is outside the range of en_US.UTF-8"
        type: string
        required: false
        default: "en_US.UTF-8"
      debug:
        description: "Enable debugging output"
        type: boolean
        required: false
        default: false
    # Re-usable workflow requires secrets be explicitly passed
    secrets:
      sonar_token:
        description: "SonarQube API key/token"
        required: true

jobs:
  sonarqube-cloud:
    name: "Scan"
    runs-on: ubuntu-24.04
    steps:
      - name: "SonarQube Cloud Scan"
        # yamllint disable-line rule:line-length
        uses: lfreleng-actions/sonarqube-cloud-scan-action@bad9028f5252eb1432340d891f9b3a589f0280c1 # v0.1.2
        with:
          sonar_token: ${{ secrets.sonar_token }}
          sonar_root_cert: ${{ inputs.sonar_root_cert }}
          build_wrapper_url: ${{ inputs.build_wrapper_url }}
          build_wrapper_out_dir: ${{ inputs.build_wrapper_out_dir }}
          sonar_host_url: ${{ inputs.sonar_host_url }}
          lc_all: ${{ inputs.lc_all }}
          debug: ${{ inputs.debug }}
